GB3-1715: arrow navigation in search
gisktzh/gb3-web_ui pull request #69
Opened 2024-12-02 14:22 UTC by TIL-EBP

2024-12-13 14:20 UTC, wendlans requested changes
Hey Till, sorry I couldn't finish the review yet. But from what I saw yet I cannot approve this requests. There are currently some show stoppers in the frontend.
As for the code: I'll have a look into that probably on Monday. Maybe we'll find some time when you can give me an overview of the changes and your thoughts.

2024-12-13 14:20 UTC, wendlans commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
Sorry, found another weird behavior 🙈
1. Go to the map
2. Search for `al`
3. Wait for the addresses and maps to appear
4. Press `TAB` until you reach the first map. As you can see there is no preview in the background (temporary map) even if there should be one.
![image](https://github.com/user-attachments/assets/72060107-0467-42cb-8b1f-eee6a79ccf20)
5. Press `DOWN` once. You'll land on the first address result. Which is not something I would expect.
![image](https://github.com/user-attachments/assets/ee174cc8-8e1d-4d64-9e57-2a8191e14fed)

2024-12-13 14:20 UTC, wendlans commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
I'm really sorry, but I couldn't start analyzing the code yet. Maybe it's best if we do that together on Monday. The one thing that I saw when trying to get an overview was that you're using a whole lot of `@ViewChild` links which is usually not a good sign - Angular tends to have more logic directly in the code behind and less bindings to the DOM directly.
Also I saw that you're referencing `Component`s within `Directive`s - not sure if that's something one should do.

But as previously said I've not got the time yet to fully understand what's going on.

2025-01-16 15:52 UTC, TIL-EBP commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
removed margin that was wrongfully added

2025-01-16 15:55 UTC, TIL-EBP commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
Both work for me (maybe I have fixed this in the mean time and just forgot).

2025-01-16 15:57 UTC, TIL-EBP commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
Yes, this was left out on purpose, because the element states were to come soon. Now that they are cancelled (i think), we should look into this. I will talk to PSI about this

2025-01-24 13:40 UTC, wendlans commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
It is working again, so all good for me.

2025-01-24 13:41 UTC, wendlans commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
From the testing I presume you came up with the solution to change the whole thing into a button. Which is fine by me 👌

2025-01-24 13:42 UTC, wendlans commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
This is fixed as well

2025-01-24 13:43 UTC, wendlans commented on src/app/start-page/components/start-page-search/start-page-search.component.html
> -<div class="start-page-search">
I'll have a look at the current implementation.

2025-01-27 07:34 UTC, Tugark approved these changes
I had a look at `base-search-container` as @wendlans suggested.

I see that there is a lot of black magic going on, so have my approval 👍

2025-01-27 07:34 UTC, Tugark commented on src/app/shared/components/search/base-search-container/base-search-container.component.ts
> +  private handelArrowKey(event: KeyboardEvent, direction: 'up' | 'down') {
Typo: `handleArrowKey`

2025-01-27 08:01 UTC, TIL-EBP commented on src/app/shared/components/data-catalogue-overview-item/overview-search-result-item.component.ts
> +  // This is a workaround for OverviewSearchResultItemComponent that do not have the SearchResultIdentifierDirective applied to them (no arrow-key navigation enabled)
Nothing really. It is just not specified in the ticket (only start page and map search)

2025-01-27 08:12 UTC, TIL-EBP commented on src/app/shared/components/search/base-search-container/base-search-container.component.ts
>    private selectedResult: SearchResultIdentifierDirective | undefined;
True, it is just inside one method and can be mad a local variabel there

2025-01-27 08:22 UTC, TIL-EBP commented
@Tugark I looked at the duplications and it's just the `super`-calls from the child components to the newly created parent compoennt `base-search-container.component.ts`. 
So I think we can mark them as false positive. But you are right, I do not have permissions to do so (at least not with my github account).

2025-01-27 11:50 UTC, merged